from __future__ import annotations

import asyncio
import datetime as _dt
import re
import uuid

from github import Github
from github.GithubException import GithubException, UnknownObjectException

from servant.defs import SECRET_GITHUB_TOKEN, GlobalContext, ToolDef
from typed_json import JSON, JSONDict, coerce_str, require_obj

_REPO_FULL_NAME = "wabbit-corp/python-jeeves"
_ALLOWED_DIR_PREFIX = "servant/modules/"
_MAX_BYTES = 900_000  # GitHub Contents API is ~1MB-ish; leave headroom.


_NAME_RX = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


def _strip_fenced_code(s: str) -> str:
    """
    If the caller sends ```python ... ```, strip the fence.
    """
    s = (s or "").strip()
    if s.startswith("```"):
        lines = s.splitlines()
        if lines and lines[0].startswith("```"):
            # Drop first line (``` or ```python)
            lines = lines[1:]
            # Drop last line if it's closing ```
            if lines and lines[-1].strip() == "```":
                lines = lines[:-1]
            s = "\n".join(lines).strip()
    # Ensure trailing newline (nice diffs, fewer headaches)
    if s and not s.endswith("\n"):
        s += "\n"
    return s


def _validate_tool_name(name: str) -> str:
    name = (name or "").strip()
    if name.endswith(".py"):
        name = name[:-3].strip()

    if not _NAME_RX.match(name):
        raise ValueError(
            "Invalid tool name. Use a valid Python identifier (letters, digits, underscore), "
            "not starting with a digit."
        )

    # Avoid a few obvious footguns
    if name in {"__init__", "__main__"}:
        raise ValueError("Refusing reserved module name.")

    return name


def _tool_file_path(name: str) -> str:
    # Forced location + forced extension.
    return f"{_ALLOWED_DIR_PREFIX}{name}.py"


def _validate_file_path(path: str) -> None:
    if not path.startswith(_ALLOWED_DIR_PREFIX):
        raise ValueError(f"Tool file must be under '{_ALLOWED_DIR_PREFIX}'.")
    if ".." in path.split("/"):
        raise ValueError("Path traversal is not allowed.")
    if not path.endswith(".py"):
        raise ValueError("Tool file must be a .py file.")


def _make_branch_name(tool_name: str) -> str:
    ts = _dt.datetime.utcnow().strftime("%Y%m%d%H%M%S")
    rand = uuid.uuid4().hex[:8]
    # Branch name rules are forgiving; keep it boring.
    return f"tools/add-{tool_name}-{ts}-{rand}"


def _submit_pr_sync(ctx: GlobalContext, *, name: str, description: str, code: str) -> JSONDict:
    token = coerce_str(ctx.secrets.get(SECRET_GITHUB_TOKEN), field="github.token", allow_empty=False)

    tool_name = _validate_tool_name(name)
    file_path = _tool_file_path(tool_name)
    _validate_file_path(file_path)

    code = _strip_fenced_code(code)
    if not code.strip():
        raise ValueError("code is empty after stripping formatting.")
    if len(code.encode("utf-8")) > _MAX_BYTES:
        raise ValueError(f"code is too large (> {_MAX_BYTES} bytes).")

    gh = Github(token)
    repo = gh.get_repo(_REPO_FULL_NAME)

    base_branch = repo.default_branch
    base_sha = repo.get_branch(base_branch).commit.sha

    # Confirm file doesn't already exist on base branch
    try:
        _ = repo.get_contents(file_path, ref=base_branch)
        raise ValueError(f"Refusing to overwrite existing file: {file_path}")
    except UnknownObjectException:
        pass  # file does not exist, good

    branch = _make_branch_name(tool_name)

    # Create branch ref
    try:
        repo.create_git_ref(ref=f"refs/heads/{branch}", sha=base_sha)
    except GithubException as e:
        # If branch exists (rare with uuid), retry once.
        if getattr(e, "status", None) == 422:
            branch = _make_branch_name(tool_name)
            repo.create_git_ref(ref=f"refs/heads/{branch}", sha=base_sha)
        else:
            msg = (getattr(e, "data", {}) or {}).get("message") or str(e)
            raise RuntimeError(f"GitHub error creating branch: {msg}") from e

    commit_message = f"Add tool module: {tool_name}"
    pr_title = f"Add tool: {tool_name}"
    pr_body = (
        f"{description.strip()}\n\n" f"- Adds `{file_path}`\n" f"- Generated by `own_code_submit_new_tool_pr`\n"
    ).strip() + "\n"

    # Create file on the new branch
    try:
        repo.create_file(
            path=file_path,
            message=commit_message,
            content=code,
            branch=branch,
        )
    except GithubException as e:
        msg = (getattr(e, "data", {}) or {}).get("message") or str(e)
        raise RuntimeError(f"GitHub error creating file: {msg}") from e

    # Create PR
    try:
        pr = repo.create_pull(
            title=pr_title,
            body=pr_body,
            head=f"{repo.owner.login}:{branch}",
            base=base_branch,
        )
    except GithubException as e:
        msg = (getattr(e, "data", {}) or {}).get("message") or str(e)
        raise RuntimeError(f"GitHub error creating PR: {msg}") from e

    return {
        "ok": True,
        "repo": _REPO_FULL_NAME,
        "base_branch": base_branch,
        "branch": branch,
        "file_path": file_path,
        "pr_number": pr.number,
        "pr_url": pr.html_url,
        "pr_title": pr_title,
    }


async def own_code_submit_new_tool_pr(ctx: GlobalContext, name: str, description: str, code: str) -> JSONDict:
    """
    Async wrapper around PyGithub (which is sync).
    """
    return await asyncio.to_thread(_submit_pr_sync, ctx=ctx, name=name, description=description, code=code)


async def _own_code_submit_new_tool_pr_tool(ctx: GlobalContext, obj: JSON) -> JSONDict:
    data = require_obj(obj)
    name = data.get("name")
    code = data.get("code")
    description = data.get("description", "")
    if not isinstance(name, str) or not name.strip():
        raise ValueError("name must be a non-empty string.")
    if not isinstance(code, str) or not code.strip():
        raise ValueError("code must be a non-empty string.")
    if not isinstance(description, str):
        raise ValueError("description must be a string.")
    return await own_code_submit_new_tool_pr(ctx, name=name.strip(), description=description, code=code)


own_code_submit_new_tool_pr_schema: ToolDef = ToolDef(
    name="own_code_submit_new_tool_pr",
    function=_own_code_submit_new_tool_pr_tool,
    schema={
        "name": "own_code_submit_new_tool_pr",
        "description": (
            "Creates a PR against wabbit-corp/python-jeeves that adds a new .py tool module under " "servant/modules/."
        ),
        "parameters": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "description": "Tool module name (Python identifier). File becomes servant/modules/<name>.py",
                },
                "description": {
                    "type": "string",
                    "description": "Human description placed in the PR body.",
                },
                "code": {
                    "type": "string",
                    "description": "Python source code for the new module.",
                },
            },
            "required": ["name", "code"],
        },
    },
)
