from typing import Any, Optional

class tzwhere:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def tzNameAt(self, lat: float, lon: float, forceTZ: bool = ...) -> Optional[str]: ...
