from collections.abc import Sequence

class RandomForestClassifier:
    def __init__(self, n_estimators: int = ...) -> None: ...
    def fit(self, X: object, y: object) -> RandomForestClassifier: ...
    def predict(self, X: object) -> Sequence[int]: ...
    def predict_proba(self, X: object) -> Sequence[Sequence[float]]: ...
